allowBuilds:
  esbuild: set this to true or false
minimumReleaseAgeExclude:
  - '@aws-sdk/client-cognito-identity-provider@3.1050.0'
  - '@aws-sdk/client-dynamodb@3.1050.0'
  - '@aws-sdk/lib-dynamodb@3.1050.0'
  - '@types/node@25.9.1'
  - '@types/react@19.2.15'
