export enum ErrorCode {
	VALIDATION = 'VALIDATION',
	EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE',
	INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
	INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
	RESET_PASSWORD_CODE_WRONG = 'RESET_PASSWORD_CODE_WRONG',
	EXPIRED_PASSWORD_CODE = 'EXPIRED_PASSWORD_CODE',
	USER_NOT_FOUND = 'USER_NOT_FOUND',
	RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
	RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',

	// HTTP
	INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
	BAD_REQUEST = 'BAD_REQUEST',
	CONFLICT = 'CONFLICT',
	UNAUTHORIZED = 'UNAUTHORIZED',
	FORBIDDEN = 'FORBIDDEN'
}
