statements:
  - Effect: Allow
    Action:
      - dynamodb:PutItem
      - dynamodb:Query
      - dynamodb:GetItem
      - dynamodb:DeleteItem
      - dynamodb:UpdateItem
      - dynamodb:BatchWriteItem
    Resource:
      - !GetAtt MainTable.Arn
      - !Sub '${MainTable.Arn}/index/*'
  - Effect: Allow
    Action:
      - cognito-idp:AdminDeleteUser
      - cognito-idp:AdminAddUserToGroup
    Resource: !GetAtt UserPool.Arn
  - Effect: Allow
    Action:
      - s3:PutObject
    Resource: !Sub '${UploadsBucket.Arn}/scans/*'
